---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: poolboy build config and imagestrem
  name: poolboy-build

parameters:
- name: NAME
  value: poolboy
- name: GIT_REPO
  value: https://github.com/rhpds/poolboy.git
- name: GIT_REF
  value: main

objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: ${GIT_REPO}
        ref: ${GIT_REF}
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: Containerfile
    triggers: []
...
