{{- if .Values.deploy -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "poolboy.name" . }}
  namespace: {{ include "poolboy.namespaceName" . }}
  labels:
    {{- include "poolboy.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "poolboy.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "poolboy.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: operator
    spec:
      containers:
        - name: manager
          env:
          - name: KOPF_OPERATORS
            value: main.py
          - name: CLUSTER_DOMAIN
            value: "{{ .Values.clusterDomain }}"
          - name: IS_STANDALONE
            value: {{ include "poolboy.isStandalone" . | quote }}
          - name: OPERATOR_DOMAIN
            value: {{ include "poolboy.operatorDomain" . }}
          {{- if .Values.enablePrometheusMetrics}}
          - name: METRICS_ENABLED
            value: "true"
          {{- end }}
          - name: RESOURCE_REFRESH_INTERVAL
            value: "{{ .Values.resourceRefreshInterval }}"
          {{- if .Values.worker.enabled }}
          envFrom:
            - configMapRef:
                name: {{ include "poolboy.name" . }}-useworkers-cm
          {{- end }}
          image: "{{ include "poolboy.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          ports:
          - name: kopf
            containerPort: 8080
          - name: metrics
            containerPort: 9090
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      serviceAccountName: {{ include "poolboy.serviceAccountName" . }}
      terminationGracePeriodSeconds: 30
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
