{{- if .Values.enablePrometheusMetrics -}}
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: {{ include "poolboy.name" . }}-metrics-credentials
  namespace: {{ include "poolboy.namespaceName" . }}
  labels:
    {{- include "poolboy.labels" . | nindent 4 }}
  annotations:
    secret-generator.v1.mittwald.de/type: basic-auth
spec:
  forceRegenerate: false
  data:
    metrics_username: {{ .Values.metrics.username }}
  fields:
  - fieldName: metrics_password
    encoding: "hex"
    length: "32"
{{- end }}
