{{- if .Values.enablePrometheusMetrics -}}
{{- $secretName := printf "%s-metrics-credentials" (include "poolboy.name" .) }}
{{- $existingSecret := lookup "v1" "Secret" (include "poolboy.namespaceName" .) $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "poolboy.namespaceName" . }}
  labels:
    {{- include "poolboy.labels" . | nindent 4 }}
type: Opaque
data:
  metrics_username: {{ .Values.metrics.username | b64enc }}
  {{- if and $existingSecret $existingSecret.data.metrics_password }}
  metrics_password: {{ $existingSecret.data.metrics_password }}
  {{- else }}
  metrics_password: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
{{- end }}
