{{- if .Values.enablePrometheusMetrics -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "poolboy.name" . }}-monitor
  namespace: {{ include "poolboy.namespaceName" . }}
  labels:
    {{- include "poolboy.labels" . | nindent 4 }}
spec:
  selector:
  matchLabels:
    {{- include "poolboy.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
    - {{ include "poolboy.namespaceName" . }}
  endpoints:
  - port: prometheus
    interval: "30s"
    path: /metrics
{{- end }}
