{{- if or .Values.redis.enabled (eq .Values.operatorMode "distributed") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "poolboy.name" . }}-redis
  namespace: {{ include "poolboy.namespaceName" . }}
  labels:
    {{- include "poolboy.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    {{- include "poolboy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
